framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
            crowdin:
                dsn: '%env(CROWDIN_DSN)%'
                locales: ['en', 'es']
                domains: ['messages']

        enabled_locale: ['en', 'es']
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
